### ISSUE TITLE
Provided MathGL (1.11) fails to compile

### ISSUE THREAD

**Issue by christopherlovell** [thierry-sousbie/DisPerSE#2]
On Ubuntu (GNOME) 16.04

```
$ ./configure --enable-qt
$ make
```

```
....
mv -f .deps/libmgl_la-mgl_parse.Tpo .deps/libmgl_la-mgl_parse.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../include/mgl    -DWITH_QT    -DMGL_FONT_PATH=\"/usr/local/share/mathgl/fonts/\" -DMOD_LIB_DIR=\"/usr/local/lib/mgl/\"         -Wall -I/usr/include -I../include -I../include -DHAVE_PTHREAD -g -O2 -MT libmgl_la-mgl_fit.lo -MD -MP -MF .deps/libmgl_la-mgl_fit.Tpo -c -o libmgl_la-mgl_fit.lo `test -f 'mgl_fit.cpp' || echo './'`mgl_fit.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../include/mgl -DWITH_QT -DMGL_FONT_PATH=\"/usr/local/share/mathgl/fonts/\" -DMOD_LIB_DIR=\"/usr/local/lib/mgl/\" -Wall -I/usr/include -I../include -I../include -DHAVE_PTHREAD -g -O2 -MT libmgl_la-mgl_fit.lo -MD -MP -MF .deps/libmgl_la-mgl_fit.Tpo -c mgl_fit.cpp  -fPIC -DPIC -o .libs/libmgl_la-mgl_fit.o
mgl_fit.cpp: In function 'mreal mgl_fit_base(mglFitData*, mreal*)':
mgl_fit.cpp:114:25: error: 'struct gsl_multifit_fdfsolver' has no member named 'J'
  gsl_multifit_covar (s->J, 0.0, covar );
                         ^
Makefile:699: recipe for target 'libmgl_la-mgl_fit.lo' failed
make[1]: *** [libmgl_la-mgl_fit.lo] Error 1
make[1]: Leaving directory '/home/chris/src/mathgl-1.11.3-2/mgl'
Makefile:389: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```

**Comment by thierry-sousbie** [comment]
This is because this version of mgl is meant to work with version 1.1X of GSL: it is not compatible with GSL2.XX. This should work if you link to the appropriate version (sorry, but I don't have time to fix this now ...)

**Comment by alexmyczko** [comment]
Meanwhile there's basic working debian packages for you to build from source package and install (without mathgl/pdview support):

http://sid.ethz.ch/debian/disperse/

**Comment by SteBarsanti** [comment]
Hi all,

I am trying to install DisPerSe on my Mac and I found the same issue. How did you link the previous GSL version?  I tried to download and install the 1.15 version from https://ftp.gnu.org/gnu/gsl/  but it doesn't work. Any other suggestion? Thanks!
